language: node_js
node_js:
  - '8'
  - '10'
sudo: false
services:
  - docker

before_install:
  - docker-compose up -d
  - sleep 120 # todo: write detection script

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm test